### ISSUE TITLE
再現性のないバグ

### ISSUE THREAD

**Issue by oikawa-ryo0623** [M-shimizu-dpt/lifegame#100]
Player一人、CPU3人で動作させていた際に特急カードを使用すると次の人に順番がまわってしまう問題
Player4人、で動作させていた際にダビングカードを使用すると次の人がカードボタンを押せない問題

どちらも同じ状況で何度か動作させたが、再現性がない。
もっと別の問題の可能性があるので、原因を突き止めてほしい

**Comment by M-shimizu-dpt** [comment]
環境の変化により一時close
