### ISSUE TITLE
スタート画面での操作の簡略化

### ISSUE THREAD

**Issue by M-shimizu-dpt** [M-shimizu-dpt/lifegame#119]
現在(10/5)、スタート画面ではキーボードから年数やプレイヤーの人数を指定するようになっている。
これでは、想定と違う年数やプレイヤー数を入力された場合の処理を書く必要が出てくる為、手間になってしまう。
そこで、リストから選ぶ方式にすることでユーザビリティを意識したUI設計を図る。

・改善点
1)キーボードから入力していた年数をリスト化(JList等を用いる想定)する.
2)プレイヤー数選択で全てのパターンのボタンを用意する.
3)プレイヤー数の選択　→　プレイヤー名の設定　→　プレイ年数の選択
のようにフレーム切り替えをする.

**Comment by satsukiTomo** [comment]
まだ少し修正の必要あり

**Comment by satsukiTomo** [comment]
現在、改善中です

**Comment by satsukiTomo** [comment]
初期設定画面の更新完了

将来的には設定した内容が修正できるようにしても良いのではないでしょうか？

**Comment by M-shimizu-dpt** [comment]
いい案ですね
その内容をissueに残しておいてくれますか？

個人的にはcpuとなったプレイヤーの名前が"P"のままになるのは分かりづらいと思うのでフレームを分けて、
cpuの数に応じてTextFieldのデフォルトが変わるようにしても良いかなと思いますがどうでしょう？

**Comment by satsukiTomo** [comment]
良いと思います
