### ISSUE TITLE
デバッグモードオフ時のContainsEventにおけるバグについて

### ISSUE THREAD

**Issue by M-shimizu-dpt** [M-shimizu-dpt/lifegame#127]
現在(10/5)、initBinbo()で引数をfalseにした場合、ボンビーがついたプレイヤーがおらずContainsEventでエラーが出るバグが確認されている為、改善を求む

**Comment by oikawa-ryo0623** [comment]
なにかの拍子で別のContainsEventを呼んでいた模様
解決した。
