### ISSUE TITLE
牛歩カードの仕様変更

### ISSUE THREAD

**Issue by M-shimizu-dpt** [M-shimizu-dpt/lifegame#140]
現在(10/7)、牛歩カードは適用されたプレイヤーの移動可能マスを-3するようになっている(移動可能マスが0以下になる場合1となる)
これでもいいのだが、本家の牛歩カードは適用されたプレイヤーはターンが回ってきたら1マス移動することしかできなかったはずなので仕様変更をしたい。

・変更内容
1)牛歩カードの効果を変更し、数ターンの間1マスしか進めないようにする
2)informationバー周りの調整をする

・注意点
1)牛歩カードの効果が適用されたプレイヤーのターンになった場合、Frameのinformationバーが切り替わるようになっている為、Frame周り(PlayFrame,GingaFrame)を確認し変更する。

**Comment by satsukiTomo** [comment]
実際にカードを使用したところ、使用したplayerが適用されていたので修正します
