### ISSUE TITLE
ぶっとびカード使用後にマスイベントが発生している

### ISSUE THREAD

**Issue by M-shimizu-dpt** [M-shimizu-dpt/lifegame#142]
現在(10/8)、ぶっとびカード使用後にマスイベントが発生している
本来、ぶっとびカードでは移動先のマスイベントが発生することはないはずなので改善する

・改善点
1)ぶっとびカード使用後にマスイベントが発生しないようにする
2)ぶっとびカード以外のランダム移動カードの仕様を確認し仕様通りに実装できているか再確認する

**Comment by oikawa-ryo0623** [comment]
完了
