### ISSUE TITLE
bonbycatchメソッドの実装

### ISSUE THREAD

**Issue by M-shimizu-dpt** [M-shimizu-dpt/lifegame#46]
現在(9/22)、bonbycatchメソッドでは各プレイヤーの目的地までの最短距離を取得しその結果を基にボンビーを付けるプレイヤーの選出をしている。
しかし、機能拡張によりこの部分にバグが発生した。
このバグの修正を行う。
(debugで検索を書けると、bonbycatchメソッドをコメントアウトしている部分に飛べる)

**Comment by oikawa-ryo0623** [comment]
原因の一つとして、ゴールが決まる前に探索していた。
なので、goal処理が終了してからbonbyメソッドを処理するように変更することで、バグの対処を行い、修正した。
