### ISSUE TITLE
SearcherクラスのsearchShortestRouteAllPlayersメソッド修正について

### ISSUE THREAD

**Issue by oikawa-ryo0623** [M-shimizu-dpt/lifegame#78]
現在(9/25)、プレイヤーたちのゴールまでの距離を探索して、プレイヤーのフィールドにその距離を代入しているメソッド
確認してみるとプレイヤーのゴールまでの距離は代入されているが、探索が終わらない。
これではだれかがゴールした際に長時間待つことになってしまう。
なので、以下の機能の改善をお願いします。

・機能
1)ゴールまでの探索し、成功した際には探索終了

**Comment by M-shimizu-dpt** [comment]
適切な範囲での再探索で終了するように改善
